/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     PyVarObject ob_base;
 *     Py_ssize_t ob_alloc;
 *     char *ob_bytes;
 *     char *ob_start;
 *     Py_ssize_t ob_exports;
 * }
 * }
 */
public class PyByteArrayObject {

    PyByteArrayObject() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        PyVarObject.layout().withName("ob_base"),
        Python_h.C_LONG.withName("ob_alloc"),
        Python_h.C_POINTER.withName("ob_bytes"),
        Python_h.C_POINTER.withName("ob_start"),
        Python_h.C_LONG.withName("ob_exports")
    ).withName("$anon$6:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ob_base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ob_base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static final GroupLayout ob_base$layout() {
        return ob_base$LAYOUT;
    }

    private static final long ob_base$OFFSET = $LAYOUT.byteOffset(groupElement("ob_base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static final long ob_base$offset() {
        return ob_base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static MemorySegment ob_base(MemorySegment struct) {
        return struct.asSlice(ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static void ob_base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    private static final OfLong ob_alloc$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ob_alloc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_alloc
     * }
     */
    public static final OfLong ob_alloc$layout() {
        return ob_alloc$LAYOUT;
    }

    private static final long ob_alloc$OFFSET = $LAYOUT.byteOffset(groupElement("ob_alloc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_alloc
     * }
     */
    public static final long ob_alloc$offset() {
        return ob_alloc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_alloc
     * }
     */
    public static long ob_alloc(MemorySegment struct) {
        return struct.get(ob_alloc$LAYOUT, ob_alloc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_alloc
     * }
     */
    public static void ob_alloc(MemorySegment struct, long fieldValue) {
        struct.set(ob_alloc$LAYOUT, ob_alloc$OFFSET, fieldValue);
    }

    private static final AddressLayout ob_bytes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ob_bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *ob_bytes
     * }
     */
    public static final AddressLayout ob_bytes$layout() {
        return ob_bytes$LAYOUT;
    }

    private static final long ob_bytes$OFFSET = $LAYOUT.byteOffset(groupElement("ob_bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *ob_bytes
     * }
     */
    public static final long ob_bytes$offset() {
        return ob_bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *ob_bytes
     * }
     */
    public static MemorySegment ob_bytes(MemorySegment struct) {
        return struct.get(ob_bytes$LAYOUT, ob_bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *ob_bytes
     * }
     */
    public static void ob_bytes(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ob_bytes$LAYOUT, ob_bytes$OFFSET, fieldValue);
    }

    private static final AddressLayout ob_start$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ob_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *ob_start
     * }
     */
    public static final AddressLayout ob_start$layout() {
        return ob_start$LAYOUT;
    }

    private static final long ob_start$OFFSET = $LAYOUT.byteOffset(groupElement("ob_start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *ob_start
     * }
     */
    public static final long ob_start$offset() {
        return ob_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *ob_start
     * }
     */
    public static MemorySegment ob_start(MemorySegment struct) {
        return struct.get(ob_start$LAYOUT, ob_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *ob_start
     * }
     */
    public static void ob_start(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ob_start$LAYOUT, ob_start$OFFSET, fieldValue);
    }

    private static final OfLong ob_exports$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ob_exports"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_exports
     * }
     */
    public static final OfLong ob_exports$layout() {
        return ob_exports$LAYOUT;
    }

    private static final long ob_exports$OFFSET = $LAYOUT.byteOffset(groupElement("ob_exports"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_exports
     * }
     */
    public static final long ob_exports$offset() {
        return ob_exports$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_exports
     * }
     */
    public static long ob_exports(MemorySegment struct) {
        return struct.get(ob_exports$LAYOUT, ob_exports$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Py_ssize_t ob_exports
     * }
     */
    public static void ob_exports(MemorySegment struct, long fieldValue) {
        struct.set(ob_exports$LAYOUT, ob_exports$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

