/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PyMethodDef {
 *     const char *ml_name;
 *     PyCFunction ml_meth;
 *     int ml_flags;
 *     const char *ml_doc;
 * }
 * }
 */
public class PyMethodDef {

    PyMethodDef() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("ml_name"),
        Python_h.C_POINTER.withName("ml_meth"),
        Python_h.C_INT.withName("ml_flags"),
        MemoryLayout.paddingLayout(4),
        Python_h.C_POINTER.withName("ml_doc")
    ).withName("PyMethodDef");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout ml_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ml_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *ml_name
     * }
     */
    public static final AddressLayout ml_name$layout() {
        return ml_name$LAYOUT;
    }

    private static final long ml_name$OFFSET = $LAYOUT.byteOffset(groupElement("ml_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *ml_name
     * }
     */
    public static final long ml_name$offset() {
        return ml_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *ml_name
     * }
     */
    public static MemorySegment ml_name(MemorySegment struct) {
        return struct.get(ml_name$LAYOUT, ml_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *ml_name
     * }
     */
    public static void ml_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ml_name$LAYOUT, ml_name$OFFSET, fieldValue);
    }

    private static final AddressLayout ml_meth$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ml_meth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyCFunction ml_meth
     * }
     */
    public static final AddressLayout ml_meth$layout() {
        return ml_meth$LAYOUT;
    }

    private static final long ml_meth$OFFSET = $LAYOUT.byteOffset(groupElement("ml_meth"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyCFunction ml_meth
     * }
     */
    public static final long ml_meth$offset() {
        return ml_meth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyCFunction ml_meth
     * }
     */
    public static MemorySegment ml_meth(MemorySegment struct) {
        return struct.get(ml_meth$LAYOUT, ml_meth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyCFunction ml_meth
     * }
     */
    public static void ml_meth(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ml_meth$LAYOUT, ml_meth$OFFSET, fieldValue);
    }

    private static final OfInt ml_flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ml_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ml_flags
     * }
     */
    public static final OfInt ml_flags$layout() {
        return ml_flags$LAYOUT;
    }

    private static final long ml_flags$OFFSET = $LAYOUT.byteOffset(groupElement("ml_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ml_flags
     * }
     */
    public static final long ml_flags$offset() {
        return ml_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ml_flags
     * }
     */
    public static int ml_flags(MemorySegment struct) {
        return struct.get(ml_flags$LAYOUT, ml_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ml_flags
     * }
     */
    public static void ml_flags(MemorySegment struct, int fieldValue) {
        struct.set(ml_flags$LAYOUT, ml_flags$OFFSET, fieldValue);
    }

    private static final AddressLayout ml_doc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ml_doc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *ml_doc
     * }
     */
    public static final AddressLayout ml_doc$layout() {
        return ml_doc$LAYOUT;
    }

    private static final long ml_doc$OFFSET = $LAYOUT.byteOffset(groupElement("ml_doc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *ml_doc
     * }
     */
    public static final long ml_doc$offset() {
        return ml_doc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *ml_doc
     * }
     */
    public static MemorySegment ml_doc(MemorySegment struct) {
        return struct.get(ml_doc$LAYOUT, ml_doc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *ml_doc
     * }
     */
    public static void ml_doc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ml_doc$LAYOUT, ml_doc$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

