/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _py_trashcan {
 *     int delete_nesting;
 *     PyObject *delete_later;
 * }
 * }
 */
public class _py_trashcan {

    _py_trashcan() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_INT.withName("delete_nesting"),
        MemoryLayout.paddingLayout(4),
        Python_h.C_POINTER.withName("delete_later")
    ).withName("_py_trashcan");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt delete_nesting$LAYOUT = (OfInt)$LAYOUT.select(groupElement("delete_nesting"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static final OfInt delete_nesting$layout() {
        return delete_nesting$LAYOUT;
    }

    private static final long delete_nesting$OFFSET = $LAYOUT.byteOffset(groupElement("delete_nesting"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static final long delete_nesting$offset() {
        return delete_nesting$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static int delete_nesting(MemorySegment struct) {
        return struct.get(delete_nesting$LAYOUT, delete_nesting$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int delete_nesting
     * }
     */
    public static void delete_nesting(MemorySegment struct, int fieldValue) {
        struct.set(delete_nesting$LAYOUT, delete_nesting$OFFSET, fieldValue);
    }

    private static final AddressLayout delete_later$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("delete_later"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static final AddressLayout delete_later$layout() {
        return delete_later$LAYOUT;
    }

    private static final long delete_later$OFFSET = $LAYOUT.byteOffset(groupElement("delete_later"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static final long delete_later$offset() {
        return delete_later$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static MemorySegment delete_later(MemorySegment struct) {
        return struct.get(delete_later$LAYOUT, delete_later$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *delete_later
     * }
     */
    public static void delete_later(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(delete_later$LAYOUT, delete_later$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

