/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int lineno;
 *     int end_lineno;
 *     int col_offset;
 *     int end_col_offset;
 * }
 * }
 */
public class _PyCompilerSrcLocation {

    _PyCompilerSrcLocation() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_INT.withName("lineno"),
        Python_h.C_INT.withName("end_lineno"),
        Python_h.C_INT.withName("col_offset"),
        Python_h.C_INT.withName("end_col_offset")
    ).withName("$anon$35:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt lineno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lineno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int lineno
     * }
     */
    public static final OfInt lineno$layout() {
        return lineno$LAYOUT;
    }

    private static final long lineno$OFFSET = $LAYOUT.byteOffset(groupElement("lineno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int lineno
     * }
     */
    public static final long lineno$offset() {
        return lineno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int lineno
     * }
     */
    public static int lineno(MemorySegment struct) {
        return struct.get(lineno$LAYOUT, lineno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int lineno
     * }
     */
    public static void lineno(MemorySegment struct, int fieldValue) {
        struct.set(lineno$LAYOUT, lineno$OFFSET, fieldValue);
    }

    private static final OfInt end_lineno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("end_lineno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int end_lineno
     * }
     */
    public static final OfInt end_lineno$layout() {
        return end_lineno$LAYOUT;
    }

    private static final long end_lineno$OFFSET = $LAYOUT.byteOffset(groupElement("end_lineno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int end_lineno
     * }
     */
    public static final long end_lineno$offset() {
        return end_lineno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int end_lineno
     * }
     */
    public static int end_lineno(MemorySegment struct) {
        return struct.get(end_lineno$LAYOUT, end_lineno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int end_lineno
     * }
     */
    public static void end_lineno(MemorySegment struct, int fieldValue) {
        struct.set(end_lineno$LAYOUT, end_lineno$OFFSET, fieldValue);
    }

    private static final OfInt col_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("col_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int col_offset
     * }
     */
    public static final OfInt col_offset$layout() {
        return col_offset$LAYOUT;
    }

    private static final long col_offset$OFFSET = $LAYOUT.byteOffset(groupElement("col_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int col_offset
     * }
     */
    public static final long col_offset$offset() {
        return col_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int col_offset
     * }
     */
    public static int col_offset(MemorySegment struct) {
        return struct.get(col_offset$LAYOUT, col_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int col_offset
     * }
     */
    public static void col_offset(MemorySegment struct, int fieldValue) {
        struct.set(col_offset$LAYOUT, col_offset$OFFSET, fieldValue);
    }

    private static final OfInt end_col_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("end_col_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int end_col_offset
     * }
     */
    public static final OfInt end_col_offset$layout() {
        return end_col_offset$LAYOUT;
    }

    private static final long end_col_offset$OFFSET = $LAYOUT.byteOffset(groupElement("end_col_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int end_col_offset
     * }
     */
    public static final long end_col_offset$offset() {
        return end_col_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int end_col_offset
     * }
     */
    public static int end_col_offset(MemorySegment struct) {
        return struct.get(end_col_offset$LAYOUT, end_col_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int end_col_offset
     * }
     */
    public static void end_col_offset(MemorySegment struct, int fieldValue) {
        struct.set(end_col_offset$LAYOUT, end_col_offset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

