/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int32_t debugger_pending_call;
 *     char debugger_script_path[512];
 * }
 * }
 */
public class _PyRemoteDebuggerSupport {

    _PyRemoteDebuggerSupport() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_INT.withName("debugger_pending_call"),
        MemoryLayout.sequenceLayout(512, Python_h.C_CHAR).withName("debugger_script_path")
    ).withName("$anon$32:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt debugger_pending_call$LAYOUT = (OfInt)$LAYOUT.select(groupElement("debugger_pending_call"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t debugger_pending_call
     * }
     */
    public static final OfInt debugger_pending_call$layout() {
        return debugger_pending_call$LAYOUT;
    }

    private static final long debugger_pending_call$OFFSET = $LAYOUT.byteOffset(groupElement("debugger_pending_call"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t debugger_pending_call
     * }
     */
    public static final long debugger_pending_call$offset() {
        return debugger_pending_call$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t debugger_pending_call
     * }
     */
    public static int debugger_pending_call(MemorySegment struct) {
        return struct.get(debugger_pending_call$LAYOUT, debugger_pending_call$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t debugger_pending_call
     * }
     */
    public static void debugger_pending_call(MemorySegment struct, int fieldValue) {
        struct.set(debugger_pending_call$LAYOUT, debugger_pending_call$OFFSET, fieldValue);
    }

    private static final SequenceLayout debugger_script_path$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("debugger_script_path"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static final SequenceLayout debugger_script_path$layout() {
        return debugger_script_path$LAYOUT;
    }

    private static final long debugger_script_path$OFFSET = $LAYOUT.byteOffset(groupElement("debugger_script_path"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static final long debugger_script_path$offset() {
        return debugger_script_path$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static MemorySegment debugger_script_path(MemorySegment struct) {
        return struct.asSlice(debugger_script_path$OFFSET, debugger_script_path$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static void debugger_script_path(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, debugger_script_path$OFFSET, debugger_script_path$LAYOUT.byteSize());
    }

    private static long[] debugger_script_path$DIMS = { 512 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static long[] debugger_script_path$dimensions() {
        return debugger_script_path$DIMS;
    }
    private static final VarHandle debugger_script_path$ELEM_HANDLE = debugger_script_path$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static byte debugger_script_path(MemorySegment struct, long index0) {
        return (byte)debugger_script_path$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char debugger_script_path[512]
     * }
     */
    public static void debugger_script_path(MemorySegment struct, long index0, byte fieldValue) {
        debugger_script_path$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

