/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     PyObject ob_base;
 *     PyObject *ag_weakreflist;
 *     PyObject *ag_name;
 *     PyObject *ag_qualname;
 *     _PyErr_StackItem ag_exc_state;
 *     PyObject *ag_origin_or_finalizer;
 *     char ag_hooks_inited;
 *     char ag_closed;
 *     char ag_running_async;
 *     int8_t ag_frame_state;
 *     PyObject *ag_iframe[1];
 * }
 * }
 */
public class PyAsyncGenObject {

    PyAsyncGenObject() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _object.layout().withName("ob_base"),
        Python_h.C_POINTER.withName("ag_weakreflist"),
        Python_h.C_POINTER.withName("ag_name"),
        Python_h.C_POINTER.withName("ag_qualname"),
        _err_stackitem.layout().withName("ag_exc_state"),
        Python_h.C_POINTER.withName("ag_origin_or_finalizer"),
        Python_h.C_CHAR.withName("ag_hooks_inited"),
        Python_h.C_CHAR.withName("ag_closed"),
        Python_h.C_CHAR.withName("ag_running_async"),
        Python_h.C_CHAR.withName("ag_frame_state"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.sequenceLayout(1, Python_h.C_POINTER).withName("ag_iframe")
    ).withName("$anon$62:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ob_base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ob_base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static final GroupLayout ob_base$layout() {
        return ob_base$LAYOUT;
    }

    private static final long ob_base$OFFSET = $LAYOUT.byteOffset(groupElement("ob_base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static final long ob_base$offset() {
        return ob_base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static MemorySegment ob_base(MemorySegment struct) {
        return struct.asSlice(ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static void ob_base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    private static final AddressLayout ag_weakreflist$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ag_weakreflist"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *ag_weakreflist
     * }
     */
    public static final AddressLayout ag_weakreflist$layout() {
        return ag_weakreflist$LAYOUT;
    }

    private static final long ag_weakreflist$OFFSET = $LAYOUT.byteOffset(groupElement("ag_weakreflist"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *ag_weakreflist
     * }
     */
    public static final long ag_weakreflist$offset() {
        return ag_weakreflist$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *ag_weakreflist
     * }
     */
    public static MemorySegment ag_weakreflist(MemorySegment struct) {
        return struct.get(ag_weakreflist$LAYOUT, ag_weakreflist$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *ag_weakreflist
     * }
     */
    public static void ag_weakreflist(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ag_weakreflist$LAYOUT, ag_weakreflist$OFFSET, fieldValue);
    }

    private static final AddressLayout ag_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ag_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *ag_name
     * }
     */
    public static final AddressLayout ag_name$layout() {
        return ag_name$LAYOUT;
    }

    private static final long ag_name$OFFSET = $LAYOUT.byteOffset(groupElement("ag_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *ag_name
     * }
     */
    public static final long ag_name$offset() {
        return ag_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *ag_name
     * }
     */
    public static MemorySegment ag_name(MemorySegment struct) {
        return struct.get(ag_name$LAYOUT, ag_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *ag_name
     * }
     */
    public static void ag_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ag_name$LAYOUT, ag_name$OFFSET, fieldValue);
    }

    private static final AddressLayout ag_qualname$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ag_qualname"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *ag_qualname
     * }
     */
    public static final AddressLayout ag_qualname$layout() {
        return ag_qualname$LAYOUT;
    }

    private static final long ag_qualname$OFFSET = $LAYOUT.byteOffset(groupElement("ag_qualname"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *ag_qualname
     * }
     */
    public static final long ag_qualname$offset() {
        return ag_qualname$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *ag_qualname
     * }
     */
    public static MemorySegment ag_qualname(MemorySegment struct) {
        return struct.get(ag_qualname$LAYOUT, ag_qualname$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *ag_qualname
     * }
     */
    public static void ag_qualname(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ag_qualname$LAYOUT, ag_qualname$OFFSET, fieldValue);
    }

    private static final GroupLayout ag_exc_state$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ag_exc_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _PyErr_StackItem ag_exc_state
     * }
     */
    public static final GroupLayout ag_exc_state$layout() {
        return ag_exc_state$LAYOUT;
    }

    private static final long ag_exc_state$OFFSET = $LAYOUT.byteOffset(groupElement("ag_exc_state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _PyErr_StackItem ag_exc_state
     * }
     */
    public static final long ag_exc_state$offset() {
        return ag_exc_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _PyErr_StackItem ag_exc_state
     * }
     */
    public static MemorySegment ag_exc_state(MemorySegment struct) {
        return struct.asSlice(ag_exc_state$OFFSET, ag_exc_state$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _PyErr_StackItem ag_exc_state
     * }
     */
    public static void ag_exc_state(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ag_exc_state$OFFSET, ag_exc_state$LAYOUT.byteSize());
    }

    private static final AddressLayout ag_origin_or_finalizer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ag_origin_or_finalizer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *ag_origin_or_finalizer
     * }
     */
    public static final AddressLayout ag_origin_or_finalizer$layout() {
        return ag_origin_or_finalizer$LAYOUT;
    }

    private static final long ag_origin_or_finalizer$OFFSET = $LAYOUT.byteOffset(groupElement("ag_origin_or_finalizer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *ag_origin_or_finalizer
     * }
     */
    public static final long ag_origin_or_finalizer$offset() {
        return ag_origin_or_finalizer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *ag_origin_or_finalizer
     * }
     */
    public static MemorySegment ag_origin_or_finalizer(MemorySegment struct) {
        return struct.get(ag_origin_or_finalizer$LAYOUT, ag_origin_or_finalizer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *ag_origin_or_finalizer
     * }
     */
    public static void ag_origin_or_finalizer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ag_origin_or_finalizer$LAYOUT, ag_origin_or_finalizer$OFFSET, fieldValue);
    }

    private static final OfByte ag_hooks_inited$LAYOUT = (OfByte)$LAYOUT.select(groupElement("ag_hooks_inited"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char ag_hooks_inited
     * }
     */
    public static final OfByte ag_hooks_inited$layout() {
        return ag_hooks_inited$LAYOUT;
    }

    private static final long ag_hooks_inited$OFFSET = $LAYOUT.byteOffset(groupElement("ag_hooks_inited"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char ag_hooks_inited
     * }
     */
    public static final long ag_hooks_inited$offset() {
        return ag_hooks_inited$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char ag_hooks_inited
     * }
     */
    public static byte ag_hooks_inited(MemorySegment struct) {
        return struct.get(ag_hooks_inited$LAYOUT, ag_hooks_inited$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char ag_hooks_inited
     * }
     */
    public static void ag_hooks_inited(MemorySegment struct, byte fieldValue) {
        struct.set(ag_hooks_inited$LAYOUT, ag_hooks_inited$OFFSET, fieldValue);
    }

    private static final OfByte ag_closed$LAYOUT = (OfByte)$LAYOUT.select(groupElement("ag_closed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char ag_closed
     * }
     */
    public static final OfByte ag_closed$layout() {
        return ag_closed$LAYOUT;
    }

    private static final long ag_closed$OFFSET = $LAYOUT.byteOffset(groupElement("ag_closed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char ag_closed
     * }
     */
    public static final long ag_closed$offset() {
        return ag_closed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char ag_closed
     * }
     */
    public static byte ag_closed(MemorySegment struct) {
        return struct.get(ag_closed$LAYOUT, ag_closed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char ag_closed
     * }
     */
    public static void ag_closed(MemorySegment struct, byte fieldValue) {
        struct.set(ag_closed$LAYOUT, ag_closed$OFFSET, fieldValue);
    }

    private static final OfByte ag_running_async$LAYOUT = (OfByte)$LAYOUT.select(groupElement("ag_running_async"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char ag_running_async
     * }
     */
    public static final OfByte ag_running_async$layout() {
        return ag_running_async$LAYOUT;
    }

    private static final long ag_running_async$OFFSET = $LAYOUT.byteOffset(groupElement("ag_running_async"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char ag_running_async
     * }
     */
    public static final long ag_running_async$offset() {
        return ag_running_async$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char ag_running_async
     * }
     */
    public static byte ag_running_async(MemorySegment struct) {
        return struct.get(ag_running_async$LAYOUT, ag_running_async$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char ag_running_async
     * }
     */
    public static void ag_running_async(MemorySegment struct, byte fieldValue) {
        struct.set(ag_running_async$LAYOUT, ag_running_async$OFFSET, fieldValue);
    }

    private static final OfByte ag_frame_state$LAYOUT = (OfByte)$LAYOUT.select(groupElement("ag_frame_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t ag_frame_state
     * }
     */
    public static final OfByte ag_frame_state$layout() {
        return ag_frame_state$LAYOUT;
    }

    private static final long ag_frame_state$OFFSET = $LAYOUT.byteOffset(groupElement("ag_frame_state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t ag_frame_state
     * }
     */
    public static final long ag_frame_state$offset() {
        return ag_frame_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t ag_frame_state
     * }
     */
    public static byte ag_frame_state(MemorySegment struct) {
        return struct.get(ag_frame_state$LAYOUT, ag_frame_state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t ag_frame_state
     * }
     */
    public static void ag_frame_state(MemorySegment struct, byte fieldValue) {
        struct.set(ag_frame_state$LAYOUT, ag_frame_state$OFFSET, fieldValue);
    }

    private static final SequenceLayout ag_iframe$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ag_iframe"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static final SequenceLayout ag_iframe$layout() {
        return ag_iframe$LAYOUT;
    }

    private static final long ag_iframe$OFFSET = $LAYOUT.byteOffset(groupElement("ag_iframe"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static final long ag_iframe$offset() {
        return ag_iframe$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static MemorySegment ag_iframe(MemorySegment struct) {
        return struct.asSlice(ag_iframe$OFFSET, ag_iframe$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static void ag_iframe(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ag_iframe$OFFSET, ag_iframe$LAYOUT.byteSize());
    }

    private static long[] ag_iframe$DIMS = { 1 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static long[] ag_iframe$dimensions() {
        return ag_iframe$DIMS;
    }
    private static final VarHandle ag_iframe$ELEM_HANDLE = ag_iframe$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static MemorySegment ag_iframe(MemorySegment struct, long index0) {
        return (MemorySegment)ag_iframe$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * PyObject *ag_iframe[1]
     * }
     */
    public static void ag_iframe(MemorySegment struct, long index0, MemorySegment fieldValue) {
        ag_iframe$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

