/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Generated by jextract

package org.openjdk.engine.python.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     lenfunc mp_length;
 *     binaryfunc mp_subscript;
 *     objobjargproc mp_ass_subscript;
 * }
 * }
 */
public class PyMappingMethods {

    PyMappingMethods() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("mp_length"),
        Python_h.C_POINTER.withName("mp_subscript"),
        Python_h.C_POINTER.withName("mp_ass_subscript")
    ).withName("$anon$122:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout mp_length$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mp_length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static final AddressLayout mp_length$layout() {
        return mp_length$LAYOUT;
    }

    private static final long mp_length$OFFSET = $LAYOUT.byteOffset(groupElement("mp_length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static final long mp_length$offset() {
        return mp_length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static MemorySegment mp_length(MemorySegment struct) {
        return struct.get(mp_length$LAYOUT, mp_length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static void mp_length(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mp_length$LAYOUT, mp_length$OFFSET, fieldValue);
    }

    private static final AddressLayout mp_subscript$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mp_subscript"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static final AddressLayout mp_subscript$layout() {
        return mp_subscript$LAYOUT;
    }

    private static final long mp_subscript$OFFSET = $LAYOUT.byteOffset(groupElement("mp_subscript"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static final long mp_subscript$offset() {
        return mp_subscript$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static MemorySegment mp_subscript(MemorySegment struct) {
        return struct.get(mp_subscript$LAYOUT, mp_subscript$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static void mp_subscript(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mp_subscript$LAYOUT, mp_subscript$OFFSET, fieldValue);
    }

    private static final AddressLayout mp_ass_subscript$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mp_ass_subscript"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static final AddressLayout mp_ass_subscript$layout() {
        return mp_ass_subscript$LAYOUT;
    }

    private static final long mp_ass_subscript$OFFSET = $LAYOUT.byteOffset(groupElement("mp_ass_subscript"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static final long mp_ass_subscript$offset() {
        return mp_ass_subscript$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static MemorySegment mp_ass_subscript(MemorySegment struct) {
        return struct.get(mp_ass_subscript$LAYOUT, mp_ass_subscript$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static void mp_ass_subscript(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mp_ass_subscript$LAYOUT, mp_ass_subscript$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

